const words = [
  'gratitude',
  'patience',
  'understanding',
  'joy',
  'openness',
  'healing',
  'honesty',
  'enthusiasm',
  'courage',
  'peace',
  'release',
  'grace',
  'synthesis',
  'tenderness',
  'communication',
  'freedom',
  'beauty',
  'adventure',
  'love',
  'clarity',
  'purpose',
  'abundance',
  'trust',
  'responsibility',
  'flexibility',
  'forgiveness',
  'spontaneity',
  'harmony',
  'balance',
  'simplicity',
  'expectancy',
  'light',
  'faith',
  'creativity',
  'compassion',
  'humor',
  'obedience',
  'willingness',
  'surrender',
  'delight',
  'integrity'
  'efficiency',
  'purification',
  'play',
  'truth',
  'education',
  'power',
  'inspiration',
  'strength',
];

// Capture user provided parameters
const url = new URL(window.location);
const countParameter = url.searchParams.get('count');
const seedParameter = url.searchParams.get('seed');

// Map the set of words to the values generated by the PRNG
const scale = d3.scaleLinear()
  .domain([0, 1])
  .rangeRound([1, words.length]);

const today = new Date();

// Prepare to pick the words
const seed = seedParameter || today.toISOString().slice(0, 10);
const numberOfWords = countParameter ? Math.min(countParameter, words.length) : Math.min(3, words.length);

console.log(`seed: ${seed}`);
console.log(`numberOfWords: ${numberOfWords}`);

// Seed the pseudo-random number generator
const prng = Math.seedrandom(seed);

const chosenWords = [];
let runCount = 0;

while (chosenWords.length < numberOfWords) {
  runCount++;

  const generated = Math.random();
  const index = scale(generated) - 1;
  const word = words[index];
  
  const unique = !chosenWords.includes(word);

  console.log(generated, index, word, unique);
  
  if (unique) chosenWords.push(word);
}

console.log(`completed after ${runCount} iterations`);

// Add the chosen words to the page
const target = document.querySelector('.words');

chosenWords.forEach((word) => {
  const element = document.createElement('h1');
  element.setAttribute('class', 'word animated fadeIn');
  const textNode = document.createTextNode(word);
  element.appendChild(textNode);
  
  target.appendChild(element);
});
